# Generated by Django 5.2 on 2025-08-29 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(choices=[('CSE', 'be-cse'), ('IT', 'btech-it'), ('EEE', 'be-eee'), ('ICE', 'be-ice'), ('ECE', 'be-ece'), ('MECH', 'be-mech'), ('CIVIL', 'be-civil')], max_length=20)),
                ('gender', models.BooleanField(choices=[(1, 'male'), (0, 'female')])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('dept', models.CharField(choices=[('CSE', 'be-cse'), ('IT', 'btech-it'), ('EEE', 'be-eee'), ('ICE', 'be-ice'), ('ECE', 'be-ece'), ('MECH', 'be-mech'), ('CIVIL', 'be-civil')], max_length=10)),
                ('semester', models.SmallIntegerField()),
                ('course_type', models.CharField(default='N', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TimeScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('dept', models.CharField(choices=[('CSE', 'be-cse'), ('IT', 'btech-it'), ('EEE', 'be-eee'), ('ICE', 'be-ice'), ('ECE', 'be-ece'), ('MECH', 'be-mech'), ('CIVIL', 'be-civil')], max_length=10)),
                ('feed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=1)),
                ('semester', models.SmallIntegerField()),
                ('dept', models.CharField(choices=[('CSE', 'be-cse'), ('IT', 'btech-it'), ('EEE', 'be-eee'), ('ICE', 'be-ice'), ('ECE', 'be-ece'), ('MECH', 'be-mech'), ('CIVIL', 'be-civil')], max_length=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.subject')),
            ],
            options={
                'verbose_name': 'class handling',
            },
        ),
    ]
